// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tunnel/v1/tunnel.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages sent from the agent to the manager.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_HttpResponse
	//	*AgentMessage_HeartbeatPing
	//	*AgentMessage_WsData
	//	*AgentMessage_WsClose
	//	*AgentMessage_StreamData
	//	*AgentMessage_StreamEnd
	//	*AgentMessage_Register
	//	*AgentMessage_Event
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHttpResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeatPing() *HeartbeatPing {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_HeartbeatPing); ok {
			return x.HeartbeatPing
		}
	}
	return nil
}

func (x *AgentMessage) GetWsData() *WebSocketData {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_WsData); ok {
			return x.WsData
		}
	}
	return nil
}

func (x *AgentMessage) GetWsClose() *WebSocketClose {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_WsClose); ok {
			return x.WsClose
		}
	}
	return nil
}

func (x *AgentMessage) GetStreamData() *StreamData {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

func (x *AgentMessage) GetStreamEnd() *StreamEnd {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StreamEnd); ok {
			return x.StreamEnd
		}
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetEvent() *EventLog {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_HttpResponse struct {
	HttpResponse *HttpResponse `protobuf:"bytes,1,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

type AgentMessage_HeartbeatPing struct {
	HeartbeatPing *HeartbeatPing `protobuf:"bytes,2,opt,name=heartbeat_ping,json=heartbeatPing,proto3,oneof"`
}

type AgentMessage_WsData struct {
	WsData *WebSocketData `protobuf:"bytes,3,opt,name=ws_data,json=wsData,proto3,oneof"`
}

type AgentMessage_WsClose struct {
	WsClose *WebSocketClose `protobuf:"bytes,4,opt,name=ws_close,json=wsClose,proto3,oneof"`
}

type AgentMessage_StreamData struct {
	StreamData *StreamData `protobuf:"bytes,5,opt,name=stream_data,json=streamData,proto3,oneof"`
}

type AgentMessage_StreamEnd struct {
	StreamEnd *StreamEnd `protobuf:"bytes,6,opt,name=stream_end,json=streamEnd,proto3,oneof"`
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,7,opt,name=register,proto3,oneof"`
}

type AgentMessage_Event struct {
	Event *EventLog `protobuf:"bytes,8,opt,name=event,proto3,oneof"`
}

func (*AgentMessage_HttpResponse) isAgentMessage_Payload() {}

func (*AgentMessage_HeartbeatPing) isAgentMessage_Payload() {}

func (*AgentMessage_WsData) isAgentMessage_Payload() {}

func (*AgentMessage_WsClose) isAgentMessage_Payload() {}

func (*AgentMessage_StreamData) isAgentMessage_Payload() {}

func (*AgentMessage_StreamEnd) isAgentMessage_Payload() {}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Event) isAgentMessage_Payload() {}

// Messages sent from the manager to the agent.
type ManagerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ManagerMessage_HttpRequest
	//	*ManagerMessage_HeartbeatPong
	//	*ManagerMessage_WsStart
	//	*ManagerMessage_WsData
	//	*ManagerMessage_WsClose
	//	*ManagerMessage_RegisterResponse
	Payload       isManagerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerMessage) Reset() {
	*x = ManagerMessage{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerMessage) ProtoMessage() {}

func (x *ManagerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerMessage.ProtoReflect.Descriptor instead.
func (*ManagerMessage) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerMessage) GetPayload() isManagerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ManagerMessage) GetHttpRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *ManagerMessage) GetHeartbeatPong() *HeartbeatPong {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_HeartbeatPong); ok {
			return x.HeartbeatPong
		}
	}
	return nil
}

func (x *ManagerMessage) GetWsStart() *WebSocketStart {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_WsStart); ok {
			return x.WsStart
		}
	}
	return nil
}

func (x *ManagerMessage) GetWsData() *WebSocketData {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_WsData); ok {
			return x.WsData
		}
	}
	return nil
}

func (x *ManagerMessage) GetWsClose() *WebSocketClose {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_WsClose); ok {
			return x.WsClose
		}
	}
	return nil
}

func (x *ManagerMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

type isManagerMessage_Payload interface {
	isManagerMessage_Payload()
}

type ManagerMessage_HttpRequest struct {
	HttpRequest *HttpRequest `protobuf:"bytes,1,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type ManagerMessage_HeartbeatPong struct {
	HeartbeatPong *HeartbeatPong `protobuf:"bytes,2,opt,name=heartbeat_pong,json=heartbeatPong,proto3,oneof"`
}

type ManagerMessage_WsStart struct {
	WsStart *WebSocketStart `protobuf:"bytes,3,opt,name=ws_start,json=wsStart,proto3,oneof"`
}

type ManagerMessage_WsData struct {
	WsData *WebSocketData `protobuf:"bytes,4,opt,name=ws_data,json=wsData,proto3,oneof"`
}

type ManagerMessage_WsClose struct {
	WsClose *WebSocketClose `protobuf:"bytes,5,opt,name=ws_close,json=wsClose,proto3,oneof"`
}

type ManagerMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,6,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

func (*ManagerMessage_HttpRequest) isManagerMessage_Payload() {}

func (*ManagerMessage_HeartbeatPong) isManagerMessage_Payload() {}

func (*ManagerMessage_WsStart) isManagerMessage_Payload() {}

func (*ManagerMessage_WsData) isManagerMessage_Payload() {}

func (*ManagerMessage_WsClose) isManagerMessage_Payload() {}

func (*ManagerMessage_RegisterResponse) isManagerMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentToken    string                 `protobuf:"bytes,1,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *HttpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *HttpResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// StreamData carries incremental HTTP response body chunks.
type StreamData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *StreamData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEnd) Reset() {
	*x = StreamEnd{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnd) ProtoMessage() {}

func (x *StreamEnd) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnd.ProtoReflect.Descriptor instead.
func (*StreamEnd) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *StreamEnd) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{8}
}

type HeartbeatPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{9}
}

type WebSocketStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketStart) Reset() {
	*x = WebSocketStart{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketStart) ProtoMessage() {}

func (x *WebSocketStart) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketStart.ProtoReflect.Descriptor instead.
func (*WebSocketStart) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *WebSocketStart) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *WebSocketStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WebSocketStart) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *WebSocketStart) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type WebSocketData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	MessageType   int32                  `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketData) Reset() {
	*x = WebSocketData{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketData) ProtoMessage() {}

func (x *WebSocketData) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketData.ProtoReflect.Descriptor instead.
func (*WebSocketData) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{11}
}

func (x *WebSocketData) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *WebSocketData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WebSocketData) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

type WebSocketClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketClose) Reset() {
	*x = WebSocketClose{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketClose) ProtoMessage() {}

func (x *WebSocketClose) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketClose.ProtoReflect.Descriptor instead.
func (*WebSocketClose) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{12}
}

func (x *WebSocketClose) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// EventLog carries an event emitted on an agent and synced to manager.
type EventLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,6,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName  string                 `protobuf:"bytes,7,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	UserId        string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,10,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLog) Reset() {
	*x = EventLog{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLog) ProtoMessage() {}

func (x *EventLog) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLog.ProtoReflect.Descriptor instead.
func (*EventLog) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{13}
}

func (x *EventLog) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventLog) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EventLog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventLog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventLog) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *EventLog) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *EventLog) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *EventLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventLog) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EventLog) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

var File_tunnel_v1_tunnel_proto protoreflect.FileDescriptor

const file_tunnel_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x16tunnel/v1/tunnel.proto\x12\ttunnel.v1\"\xe1\x03\n" +
	"\fAgentMessage\x12>\n" +
	"\rhttp_response\x18\x01 \x01(\v2\x17.tunnel.v1.HttpResponseH\x00R\fhttpResponse\x12A\n" +
	"\x0eheartbeat_ping\x18\x02 \x01(\v2\x18.tunnel.v1.HeartbeatPingH\x00R\rheartbeatPing\x123\n" +
	"\aws_data\x18\x03 \x01(\v2\x18.tunnel.v1.WebSocketDataH\x00R\x06wsData\x126\n" +
	"\bws_close\x18\x04 \x01(\v2\x19.tunnel.v1.WebSocketCloseH\x00R\awsClose\x128\n" +
	"\vstream_data\x18\x05 \x01(\v2\x15.tunnel.v1.StreamDataH\x00R\n" +
	"streamData\x125\n" +
	"\n" +
	"stream_end\x18\x06 \x01(\v2\x14.tunnel.v1.StreamEndH\x00R\tstreamEnd\x128\n" +
	"\bregister\x18\a \x01(\v2\x1a.tunnel.v1.RegisterRequestH\x00R\bregister\x12+\n" +
	"\x05event\x18\b \x01(\v2\x13.tunnel.v1.EventLogH\x00R\x05eventB\t\n" +
	"\apayload\"\x8c\x03\n" +
	"\x0eManagerMessage\x12;\n" +
	"\fhttp_request\x18\x01 \x01(\v2\x16.tunnel.v1.HttpRequestH\x00R\vhttpRequest\x12A\n" +
	"\x0eheartbeat_pong\x18\x02 \x01(\v2\x18.tunnel.v1.HeartbeatPongH\x00R\rheartbeatPong\x126\n" +
	"\bws_start\x18\x03 \x01(\v2\x19.tunnel.v1.WebSocketStartH\x00R\awsStart\x123\n" +
	"\aws_data\x18\x04 \x01(\v2\x18.tunnel.v1.WebSocketDataH\x00R\x06wsData\x126\n" +
	"\bws_close\x18\x05 \x01(\v2\x19.tunnel.v1.WebSocketCloseH\x00R\awsClose\x12J\n" +
	"\x11register_response\x18\x06 \x01(\v2\x1b.tunnel.v1.RegisterResponseH\x00R\x10registerResponseB\t\n" +
	"\apayload\"2\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vagent_token\x18\x01 \x01(\tR\n" +
	"agentToken\"k\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xfd\x01\n" +
	"\vHttpRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12=\n" +
	"\aheaders\x18\x05 \x03(\v2#.tunnel.v1.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\fHttpResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12>\n" +
	"\aheaders\x18\x03 \x03(\v2$.tunnel.v1.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\n" +
	"StreamData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"*\n" +
	"\tStreamEnd\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x0f\n" +
	"\rHeartbeatPing\"\x0f\n" +
	"\rHeartbeatPong\"\xd5\x01\n" +
	"\x0eWebSocketStart\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12@\n" +
	"\aheaders\x18\x04 \x03(\v2&.tunnel.v1.WebSocketStart.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\rWebSocketData\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\x05R\vmessageType\"-\n" +
	"\x0eWebSocketClose\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"\xb7\x02\n" +
	"\bEventLog\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x06 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\a \x01(\tR\fresourceName\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x12#\n" +
	"\rmetadata_json\x18\n" +
	" \x01(\fR\fmetadataJson2R\n" +
	"\rTunnelService\x12A\n" +
	"\aConnect\x12\x17.tunnel.v1.AgentMessage\x1a\x19.tunnel.v1.ManagerMessage(\x010\x01BTZRgithub.com/getarcaneapp/arcane/backend/pkg/libarcane/edge/proto/tunnel/v1;tunnelpbb\x06proto3"

var (
	file_tunnel_v1_tunnel_proto_rawDescOnce sync.Once
	file_tunnel_v1_tunnel_proto_rawDescData []byte
)

func file_tunnel_v1_tunnel_proto_rawDescGZIP() []byte {
	file_tunnel_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_tunnel_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnel_v1_tunnel_proto_rawDesc), len(file_tunnel_v1_tunnel_proto_rawDesc)))
	})
	return file_tunnel_v1_tunnel_proto_rawDescData
}

var file_tunnel_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_tunnel_v1_tunnel_proto_goTypes = []any{
	(*AgentMessage)(nil),     // 0: tunnel.v1.AgentMessage
	(*ManagerMessage)(nil),   // 1: tunnel.v1.ManagerMessage
	(*RegisterRequest)(nil),  // 2: tunnel.v1.RegisterRequest
	(*RegisterResponse)(nil), // 3: tunnel.v1.RegisterResponse
	(*HttpRequest)(nil),      // 4: tunnel.v1.HttpRequest
	(*HttpResponse)(nil),     // 5: tunnel.v1.HttpResponse
	(*StreamData)(nil),       // 6: tunnel.v1.StreamData
	(*StreamEnd)(nil),        // 7: tunnel.v1.StreamEnd
	(*HeartbeatPing)(nil),    // 8: tunnel.v1.HeartbeatPing
	(*HeartbeatPong)(nil),    // 9: tunnel.v1.HeartbeatPong
	(*WebSocketStart)(nil),   // 10: tunnel.v1.WebSocketStart
	(*WebSocketData)(nil),    // 11: tunnel.v1.WebSocketData
	(*WebSocketClose)(nil),   // 12: tunnel.v1.WebSocketClose
	(*EventLog)(nil),         // 13: tunnel.v1.EventLog
	nil,                      // 14: tunnel.v1.HttpRequest.HeadersEntry
	nil,                      // 15: tunnel.v1.HttpResponse.HeadersEntry
	nil,                      // 16: tunnel.v1.WebSocketStart.HeadersEntry
}
var file_tunnel_v1_tunnel_proto_depIdxs = []int32{
	5,  // 0: tunnel.v1.AgentMessage.http_response:type_name -> tunnel.v1.HttpResponse
	8,  // 1: tunnel.v1.AgentMessage.heartbeat_ping:type_name -> tunnel.v1.HeartbeatPing
	11, // 2: tunnel.v1.AgentMessage.ws_data:type_name -> tunnel.v1.WebSocketData
	12, // 3: tunnel.v1.AgentMessage.ws_close:type_name -> tunnel.v1.WebSocketClose
	6,  // 4: tunnel.v1.AgentMessage.stream_data:type_name -> tunnel.v1.StreamData
	7,  // 5: tunnel.v1.AgentMessage.stream_end:type_name -> tunnel.v1.StreamEnd
	2,  // 6: tunnel.v1.AgentMessage.register:type_name -> tunnel.v1.RegisterRequest
	13, // 7: tunnel.v1.AgentMessage.event:type_name -> tunnel.v1.EventLog
	4,  // 8: tunnel.v1.ManagerMessage.http_request:type_name -> tunnel.v1.HttpRequest
	9,  // 9: tunnel.v1.ManagerMessage.heartbeat_pong:type_name -> tunnel.v1.HeartbeatPong
	10, // 10: tunnel.v1.ManagerMessage.ws_start:type_name -> tunnel.v1.WebSocketStart
	11, // 11: tunnel.v1.ManagerMessage.ws_data:type_name -> tunnel.v1.WebSocketData
	12, // 12: tunnel.v1.ManagerMessage.ws_close:type_name -> tunnel.v1.WebSocketClose
	3,  // 13: tunnel.v1.ManagerMessage.register_response:type_name -> tunnel.v1.RegisterResponse
	14, // 14: tunnel.v1.HttpRequest.headers:type_name -> tunnel.v1.HttpRequest.HeadersEntry
	15, // 15: tunnel.v1.HttpResponse.headers:type_name -> tunnel.v1.HttpResponse.HeadersEntry
	16, // 16: tunnel.v1.WebSocketStart.headers:type_name -> tunnel.v1.WebSocketStart.HeadersEntry
	0,  // 17: tunnel.v1.TunnelService.Connect:input_type -> tunnel.v1.AgentMessage
	1,  // 18: tunnel.v1.TunnelService.Connect:output_type -> tunnel.v1.ManagerMessage
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_tunnel_v1_tunnel_proto_init() }
func file_tunnel_v1_tunnel_proto_init() {
	if File_tunnel_v1_tunnel_proto != nil {
		return
	}
	file_tunnel_v1_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_HttpResponse)(nil),
		(*AgentMessage_HeartbeatPing)(nil),
		(*AgentMessage_WsData)(nil),
		(*AgentMessage_WsClose)(nil),
		(*AgentMessage_StreamData)(nil),
		(*AgentMessage_StreamEnd)(nil),
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Event)(nil),
	}
	file_tunnel_v1_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*ManagerMessage_HttpRequest)(nil),
		(*ManagerMessage_HeartbeatPong)(nil),
		(*ManagerMessage_WsStart)(nil),
		(*ManagerMessage_WsData)(nil),
		(*ManagerMessage_WsClose)(nil),
		(*ManagerMessage_RegisterResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnel_v1_tunnel_proto_rawDesc), len(file_tunnel_v1_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunnel_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_tunnel_v1_tunnel_proto_depIdxs,
		MessageInfos:      file_tunnel_v1_tunnel_proto_msgTypes,
	}.Build()
	File_tunnel_v1_tunnel_proto = out.File
	file_tunnel_v1_tunnel_proto_goTypes = nil
	file_tunnel_v1_tunnel_proto_depIdxs = nil
}
